%define _debugsource_template %{nil}
%define debug_package %{nil}

%bcond_without vendored

%global app_id com.github.sachesi.rpminstall

Name:           rpm-install
Version:        0.4.0
Release:        1%{?dist}
Summary:        GTK4/libadwaita GUI installer for local RPM files via dnf5daemon or zypper

License:        GPL-3.0-or-later
URL:            https://github.com/sachesi/rpm-install
Source0:        %{url}/archive/refs/tags/v%{version}.tar.gz#/%{name}-%{version}.tar.gz
%if %{with vendored}
Source1:        %{name}-%{version}-vendor.tar.zst
%endif

BuildRequires:  cargo
BuildRequires:  rust
BuildRequires:  gcc
BuildRequires:  pkgconfig(gtk4)
BuildRequires:  pkgconfig(libadwaita-1)
BuildRequires:  desktop-file-utils

%if 0%{?suse_version}
Requires:       zypper
%else
Requires:       dnf5daemon-server
%endif

%description
GTK4/libadwaita GUI installer for local RPM files via dnf5daemon or zypper.

The application accepts local .rpm files, paths, or file:// URIs, reads package
metadata, and installs or reinstalls packages using dnf5daemon or zypper
transactions. It integrates with desktop MIME handling so RPM files can be
opened directly in the GUI.

%prep
%autosetup -n %{name}-%{version}
rm -f rust-toolchain.toml

%if %{with vendored}
# Source1 is generated by:
#   make copr
#
# It must contain:
#   vendor/
#   .cargo/config.toml
#
# The config must be generated with:
#   cargo vendor vendor > .cargo/config.toml
tar -xaf %{SOURCE1}
test -d vendor
test -f .cargo/config.toml
%endif

%build
export CARGO_HOME="$PWD/.cargo-home"
export RUSTFLAGS="%{?build_rustflags}"

%if %{with vendored}
export CARGO_NET_OFFLINE=true
cargo build --release --frozen --offline
%else
cargo build --release
%endif

%install
install -Dpm 0755 target/release/rpm-install \
  %{buildroot}%{_bindir}/rpm-install

install -Dpm 0644 packaging/%{app_id}.desktop \
  %{buildroot}%{_datadir}/applications/%{app_id}.desktop

%check
desktop-file-validate %{buildroot}%{_datadir}/applications/%{app_id}.desktop
test -x %{buildroot}%{_bindir}/rpm-install

%files
%license LICENSE*
%doc README*
%{_bindir}/rpm-install
%{_datadir}/applications/%{app_id}.desktop

%changelog
* Mon May 11 2026 sachesi <xsachesi@pm.me> - 0.4.0-1
- Add openSUSE support via Zypper backend
- Unified backend architecture for cross-distro support
- Makefile improvements for standard build/install workflows

* Sun Apr 26 2026 sachesi <xsachesi@pm.me> - 0.3.8-2
- Make vendored mode conditional and default-enabled for COPR offline rebuilds
- Allow local online builds with --without vendored

* Fri Apr 24 2026 sachesi <xsachesi@pm.me> - 0.3.8-1
- Preview dependency installs in the confirmation dialog
- Bump version to 0.3.8

* Sat Apr 18 2026 sachesi <xsachesi@pm.me> - 0.3.7-1
- Change license to GPL-3.0
- Add actual LICENSE file
- Bump version to 0.3.7

* Sat Apr 18 2026 sachesi <xsachesi@pm.me> - 0.3.6-1
- Drop appstream metainfo
- Add Settings to .desktop category

* Sat Apr 18 2026 sachesi <xsachesi@pm.me> - 0.3.5-2
- Use vendored offline COPR build
- Add .copr/Makefile

* Sat Apr 18 2026 sachesi <xsachesi@pm.me> - 0.3.5-1
- Use system themed RPM icon application-x-rpm for desktop integration
- Refresh AppStream/README release metadata for 0.3.5

* Mon Apr 06 2026 sachesi <xsachesi@pm.me> - 0.3.4-1
- Rename project from rpm-installer to rpm-install
- Rename compiled binary to rpm-install

* Mon Apr 06 2026 sachesi <xsachesi@pm.me> - 0.1.2-1
- Add colored install-state heading cues and uninstall action for installed packages
- Keep metadata/path validation and error handling hardening from stabilization pass

* Mon Apr 06 2026 sachesi <xsachesi@pm.me> - 0.1.0-1
- Initial Fedora package with COPR-friendly Source0 mode
- Keep local build-in-place workflow via --define '_build_in_place 1'
